# Basic set up for three package managers

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "spruce-bruce"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/functional"
    schedule:
      interval: "daily"
    reviewers:
      - "spruce-bruce"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/oop"
    schedule:
      interval: "daily"
    reviewers:
      - "spruce-bruce"
