name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  functional_test:
    name: "Test - Functional"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: functional
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: ".npm-cache"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - run: npm i
      - run: npm ci --cache .npm-cache --prefer-offline
      # - run: npm run test:ci

  oop_test:
    name: "Test - Object Oriented"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: oop
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: ".npm-cache"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --cache .npm-cache --prefer-offline
      - run: npm run test:ci
